
package at.ac.univie.dse2016.stream.common.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.8
 * Tue Nov 22 19:58:03 CET 2016
 * Generated source version: 3.1.8
 */

@XmlRootElement(name = "getBrokerNetworkAddress", namespace = "http://common.stream.dse2016.univie.ac.at/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getBrokerNetworkAddress", namespace = "http://common.stream.dse2016.univie.ac.at/")

public class GetBrokerNetworkAddress {

    @XmlElement(name = "arg0")
    private java.lang.Integer arg0;

    public java.lang.Integer getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.Integer newArg0)  {
        this.arg0 = newArg0;
    }

}

