
package at.ac.univie.dse2016.stream.common.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.8
 * Tue Nov 22 19:58:04 CET 2016
 * Generated source version: 3.1.8
 */

@XmlRootElement(name = "getStatusResponse", namespace = "http://common.stream.dse2016.univie.ac.at/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getStatusResponse", namespace = "http://common.stream.dse2016.univie.ac.at/")

public class GetStatusResponse {

    @XmlElement(name = "return")
    private at.ac.univie.dse2016.stream.common.BoerseStatus _return;

    public at.ac.univie.dse2016.stream.common.BoerseStatus getReturn() {
        return this._return;
    }

    public void setReturn(at.ac.univie.dse2016.stream.common.BoerseStatus new_return)  {
        this._return = new_return;
    }

}

